name: Terraform EC2 Provisioning and Ansible Setup

on:
  push:
    branches:
      - main

jobs:
  deploy_ec2:
    name: Apply Terraform EC2
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID1 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY1 }}
          aws-region: eu-north-1

      - name: Terraform Init
        working-directory: ./eks-install
        run: terraform init

      - name: Terraform Validate
        working-directory: ./eks-install
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./eks-install
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./eks-install
        run: terraform apply -auto-approve
